version: '3'
services:
  app:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - APP_URL=http://localhost:8080
      - DB_URL=jdbc:postgresql://postgres:5432/variant-annotator
      - DB_USER=postgres
      - DB_PASS=postgres
  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=variant-annotator
    volumes:
      - ./data/postgres:/var/lib/postgresql
